### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pcardune**
update grunt-contrib-compress version

### CODE REVIEW

**Review by jeremydstone — APPROVED** [review]
LGTM

**Comment by pcardune** [comment]
@jeremydstone I don't have merge rights to this repo, so you'll have to do the merge.

**Comment by pcardune** [comment]
@jeremydstone can you give me merge permissions or can you merge this change? thanks!

**Comment by jeremydstone** [comment]
@cpirich would you be able to do this merge and also publish a new Bramble version?

**Pull request merged**
